apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "bets-api-auth-policy"
spec:
  jwtRules:
    - issuer: "http://34.138.41.189/auth/realms/istio"
      jwksUri: http://34.138.41.189/auth/realms/istio/protocol/openid-connect/certs
      forwardOriginalToken: true
